on: [push, pull_request]
name: test
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15' # The Go version to download (if necessary) and use.
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Cache(on Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@preview
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**\go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Use Cache
      if: runner.os != 'Windows'
      uses: actions/cache@preview
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download Modules
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download
    - name: Run tests
      run: go test -v -covermode=atomic
